package com.joaomendonca.lifeos.workspace.application;
import com.joaomendonca.lifeos.workspace.*; import com.joaomendonca.lifeos.task.*; import com.joaomendonca.lifeos.brain.*;
import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service
public class WorkspaceDetailService {
 private final WorkspaceRepository workspaces; private final TaskRepository tasks; private final NoteRepository notes; private final ActivityEventRepository events; private final WorkspaceChecklistItemRepository checklist; private final WorkspaceAttachmentRepository attachments;
 public WorkspaceDetailService(WorkspaceRepository w,TaskRepository t,NoteRepository n,ActivityEventRepository e,WorkspaceChecklistItemRepository c,WorkspaceAttachmentRepository a){workspaces=w;tasks=t;notes=n;events=e;checklist=c;attachments=a;}
 public record TaskItem(String id,String title,String status,String priority,String context,Integer durationMinutes,java.time.LocalDate dueDate){}
 public record NoteItem(String id,String title,String content,boolean favorite,String updatedAt){}
 public record EventItem(String id,String action,String description,String entityType,String createdAt){}
 public record ChecklistItem(String id,String title,boolean completed,int position){}
 public record AttachmentItem(String id,String name,String url,String contentType,Long sizeBytes,String createdAt){}
 public record Detail(String id,String name,String description,String area,String type,String icon,String color,String status,java.time.LocalDate startDate,java.time.LocalDate dueDate,int progress,List<TaskItem> tasks,List<NoteItem> notes,List<EventItem> timeline,List<ChecklistItem> checklist,List<AttachmentItem> attachments){}
 @Transactional(readOnly=true) public Detail get(UUID id){var w=workspaces.findById(id).orElseThrow(()->new IllegalArgumentException("Workspace não encontrado."));var ts=tasks.findAllByWorkspaceIdOrderByCreatedAtDesc(id);long done=ts.stream().filter(t->t.getStatus()==TaskStatus.DONE).count();int progress=ts.isEmpty()?0:(int)Math.round(done*100d/ts.size());return new Detail(w.getId().toString(),w.getName(),w.getDescription(),w.getArea(),w.getType().name(),w.getIcon(),w.getColor(),w.getStatus(),w.getStartDate(),w.getDueDate(),progress,ts.stream().map(t->new TaskItem(t.getId().toString(),t.getTitle(),label(t.getStatus()),t.getPriority(),t.getContext(),t.getDurationMinutes(),t.getDueDate())).toList(),notes.findAllByWorkspaceIdAndArchivedFalseOrderByUpdatedAtDesc(id).stream().map(n->new NoteItem(n.getId().toString(),n.getTitle(),n.getContent(),Boolean.TRUE.equals(n.getFavorite()),n.getUpdatedAt().toString())).toList(),events.findAllByWorkspaceIdOrderByCreatedAtDesc(id).stream().map(e->new EventItem(e.getId().toString(),e.getAction(),e.getDescription(),e.getEntityType(),e.getCreatedAt().toString())).toList(),checklist.findAllByWorkspaceIdOrderByPositionAscCreatedAtAsc(id).stream().map(c->new ChecklistItem(c.getId().toString(),c.getTitle(),Boolean.TRUE.equals(c.getCompleted()),c.getPosition())).toList(),attachments.findAllByWorkspaceIdOrderByCreatedAtDesc(id).stream().map(a->new AttachmentItem(a.getId().toString(),a.getName(),a.getUrl(),a.getContentType(),a.getSizeBytes(),a.getCreatedAt().toString())).toList());}
 private String label(TaskStatus s){return switch(s){case INBOX->"Inbox";case NEXT->"Próxima";case IN_PROGRESS->"Em andamento";case DONE->"Concluída";};}
}
