package com.joaomendonca.lifeos.workspace;
import com.joaomendonca.lifeos.workspace.application.WorkspaceDetailService; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.util.*; import org.springframework.http.*; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/v1/workspaces/{workspaceId}")
public class WorkspaceContentController {
 private final WorkspaceDetailService details; private final WorkspaceRepository workspaces; private final WorkspaceChecklistItemRepository checklist; private final WorkspaceAttachmentRepository attachments;
 public WorkspaceContentController(WorkspaceDetailService d,WorkspaceRepository w,WorkspaceChecklistItemRepository c,WorkspaceAttachmentRepository a){details=d;workspaces=w;checklist=c;attachments=a;}
 record ChecklistRequest(@NotBlank @Size(max=220) String title,Integer position){}
 record AttachmentRequest(@NotBlank @Size(max=255) String name,@NotBlank String url,String contentType,Long sizeBytes){}
 @GetMapping("/detail") WorkspaceDetailService.Detail detail(@PathVariable UUID workspaceId){return details.get(workspaceId);}
 @PostMapping("/checklist") @ResponseStatus(HttpStatus.CREATED) @Transactional WorkspaceDetailService.ChecklistItem addChecklist(@PathVariable UUID workspaceId,@Valid @RequestBody ChecklistRequest r){var e=new WorkspaceChecklistItemEntity();e.setWorkspace(find(workspaceId));e.setTitle(r.title().trim());e.setPosition(r.position()==null?0:r.position());e=checklist.save(e);return new WorkspaceDetailService.ChecklistItem(e.getId().toString(),e.getTitle(),false,e.getPosition());}
 @PatchMapping("/checklist/{id}/toggle") @Transactional WorkspaceDetailService.ChecklistItem toggle(@PathVariable UUID workspaceId,@PathVariable UUID id){var e=checklist.findById(id).filter(x->x.getWorkspace().getId().equals(workspaceId)).orElseThrow(()->new IllegalArgumentException("Item não encontrado."));e.setCompleted(!Boolean.TRUE.equals(e.getCompleted()));e=checklist.save(e);return new WorkspaceDetailService.ChecklistItem(e.getId().toString(),e.getTitle(),e.getCompleted(),e.getPosition());}
 @DeleteMapping("/checklist/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional void deleteChecklist(@PathVariable UUID workspaceId,@PathVariable UUID id){var e=checklist.findById(id).filter(x->x.getWorkspace().getId().equals(workspaceId)).orElseThrow(()->new IllegalArgumentException("Item não encontrado."));checklist.delete(e);}
 @PostMapping("/attachments") @ResponseStatus(HttpStatus.CREATED) @Transactional WorkspaceDetailService.AttachmentItem addAttachment(@PathVariable UUID workspaceId,@Valid @RequestBody AttachmentRequest r){var e=new WorkspaceAttachmentEntity();e.setWorkspace(find(workspaceId));e.setName(r.name().trim());e.setUrl(r.url().trim());e.setContentType(r.contentType());e.setSizeBytes(r.sizeBytes());e=attachments.save(e);return new WorkspaceDetailService.AttachmentItem(e.getId().toString(),e.getName(),e.getUrl(),e.getContentType(),e.getSizeBytes(),e.getCreatedAt().toString());}
 @DeleteMapping("/attachments/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @Transactional void deleteAttachment(@PathVariable UUID workspaceId,@PathVariable UUID id){var e=attachments.findById(id).filter(x->x.getWorkspace().getId().equals(workspaceId)).orElseThrow(()->new IllegalArgumentException("Anexo não encontrado."));attachments.delete(e);}
 private WorkspaceEntity find(UUID id){return workspaces.findById(id).orElseThrow(()->new IllegalArgumentException("Workspace não encontrado."));}
}
