"use client";
import { useCallback, useMemo, useState } from "react";
import { CalendarPlus, Check, Clock3, Pencil, Plus, RefreshCw, Repeat2, Trash2, X } from "lucide-react";
import { lifeosApi } from "@/lib/api";
import { CalendarBlockType, CalendarDomain, RoutineDefinition, RoutineDefinitionInput } from "@/lib/types";
import { useResource } from "@/lib/use-resource";
import { PageHeader } from "./page-header";
import { SyncState } from "./sync-state";
import { useToast } from "./toast-provider";

const days=[{n:1,s:"Seg",l:"Segunda"},{n:2,s:"Ter",l:"Terça"},{n:3,s:"Qua",l:"Quarta"},{n:4,s:"Qui",l:"Quinta"},{n:5,s:"Sex",l:"Sexta"},{n:6,s:"Sáb",l:"Sábado"},{n:7,s:"Dom",l:"Domingo"}];
const domainLabels:Record<CalendarDomain,string>={WORK:"Trabalho",HEALTH:"Saúde",STUDY:"Estudo",PERSONAL:"Pessoal"};
const typeLabels:Record<CalendarBlockType,string>={FOCUS:"Foco",MEETING:"Compromisso",PERSONAL:"Pessoal",ROUTINE:"Rotina",BREAK:"Pausa"};
const empty:RoutineDefinitionInput={title:"",description:"",blockType:"ROUTINE",domain:"PERSONAL",daysOfWeek:[1],startTime:"08:00",endTime:"09:00",active:true,sortOrder:100};
function mondayIso(){const d=new Date();const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d.toISOString().slice(0,10);}

export function RoutineView(){
 const loader=useCallback(()=>lifeosApi.routineDefinitions(),[]);
 const {data,setData,loading,error,source,warning,reload}=useResource(loader,[] as RoutineDefinition[]);
 const [open,setOpen]=useState(false);const [editing,setEditing]=useState<RoutineDefinition|null>(null);const [form,setForm]=useState<RoutineDefinitionInput>(empty);const [saving,setSaving]=useState(false);const {notify}=useToast();
 const activeCount=useMemo(()=>data.filter(r=>r.active).length,[data]);
 function openNew(){setEditing(null);setForm({...empty,daysOfWeek:[1]});setOpen(true)}
 function openEdit(r:RoutineDefinition){setEditing(r);setForm({title:r.title,description:r.description,blockType:r.blockType,domain:r.domain,daysOfWeek:[...r.daysOfWeek],startTime:r.startTime.slice(0,5),endTime:r.endTime.slice(0,5),active:r.active,sortOrder:r.sortOrder});setOpen(true)}
 function toggleDay(n:number){setForm(current=>({...current,daysOfWeek:current.daysOfWeek.includes(n)?current.daysOfWeek.filter(d=>d!==n):[...current.daysOfWeek,n].sort()}))}
 async function save(){if(!form.title.trim()){notify("Informe o nome da rotina.","error");return}if(!form.daysOfWeek.length){notify("Escolha pelo menos um dia.","error");return}if(form.endTime<=form.startTime){notify("O fim deve ser posterior ao início.","error");return}setSaving(true);try{const result=editing?await lifeosApi.updateRoutineDefinition(editing.id,form):await lifeosApi.createRoutineDefinition(form);setData(current=>editing?current.map(r=>r.id===editing.id?result.data:r):[...current,result.data].sort((a,b)=>a.sortOrder-b.sortOrder));setOpen(false);notify(editing?"Rotina atualizada.":"Rotina criada.");}catch(e){notify(e instanceof Error?e.message:"Falha ao salvar.","error")}finally{setSaving(false)}}
 async function deactivate(r:RoutineDefinition){try{await lifeosApi.deleteRoutineDefinition(r.id);setData(current=>current.map(item=>item.id===r.id?{...item,active:false}:item));notify("Rotina desativada. Semanas já criadas foram preservadas.");}catch(e){notify(e instanceof Error?e.message:"Falha ao desativar.","error")}}
 async function generate(){try{const result=await lifeosApi.generateRoutineWeek(mondayIso());notify(result.data.created?`${result.data.created} blocos adicionados nesta semana.`:"A semana já está atualizada.");}catch(e){notify(e instanceof Error?e.message:"Falha ao gerar a semana.","error")}}
 return <main className="main-content routine-page"><PageHeader eyebrow="AUTOMAÇÃO PESSOAL" title="Minha Rotina" subtitle="Configure sua semana ideal uma vez. O LifeOS cria as ocorrências futuras sem alterar semanas anteriores."/>
  <div className="resource-header"><SyncState loading={loading} error={error} source={source} warning={warning} onRetry={reload}/></div>
  <section className="routine-hero panel"><div><Repeat2 size={22}/><div><strong>{activeCount} rotinas ativas</strong><span>Novas semanas são preenchidas automaticamente ao abrir a Agenda.</span></div></div><div><button className="secondary-button" onClick={()=>void generate()}><RefreshCw size={15}/>Gerar esta semana</button><button className="primary-button" onClick={openNew}><Plus size={15}/>Nova rotina</button></div></section>
  <section className="routine-grid">{data.map(r=><article className={`panel routine-card ${r.active?"":"inactive"}`} key={r.id}><header><div><span className={`routine-domain domain-${r.domain.toLowerCase()}`}>{domainLabels[r.domain]}</span><h3>{r.title}</h3></div><div><button className="icon-button ghost" onClick={()=>openEdit(r)} aria-label="Editar"><Pencil size={15}/></button>{r.active&&<button className="icon-button ghost danger" onClick={()=>void deactivate(r)} aria-label="Desativar"><Trash2 size={15}/></button>}</div></header><p>{r.description||"Sem descrição"}</p><div className="routine-days">{days.map(day=><span className={r.daysOfWeek.includes(day.n)?"active":""} key={day.n}>{day.s}</span>)}</div><footer><span><Clock3 size={14}/>{r.startTime.slice(0,5)}–{r.endTime.slice(0,5)}</span><span>{typeLabels[r.blockType]}</span>{!r.active&&<strong>Desativada</strong>}</footer></article>)}</section>
  {!loading&&!data.length&&<section className="panel routine-empty"><CalendarPlus size={30}/><h3>Crie sua semana ideal</h3><p>Cadastre trabalho, estudos, treinos, lazer e outras recorrências.</p><button className="primary-button" onClick={openNew}>Criar primeira rotina</button></section>}
  {open&&<div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-backdrop" onClick={()=>setOpen(false)} aria-label="Fechar"/><section className="entity-drawer routine-drawer"><header><div><span className="eyebrow">{editing?"EDITAR ROTINA":"NOVA ROTINA"}</span><h2>{editing?.title||"Planejar recorrência"}</h2></div><button className="icon-button ghost" onClick={()=>setOpen(false)}><X size={18}/></button></header><div className="drawer-content routine-form"><label><span>Nome</span><input autoFocus value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Ex.: Futebol"/></label><label><span>Descrição</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Informações opcionais"/></label><div className="form-grid"><label><span>Área</span><select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value as CalendarDomain})}>{Object.entries(domainLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label><span>Formato</span><select value={form.blockType} onChange={e=>setForm({...form,blockType:e.target.value as CalendarBlockType})}>{Object.entries(typeLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label></div><fieldset><legend>Dias da semana</legend><div className="routine-day-picker">{days.map(day=><button type="button" className={form.daysOfWeek.includes(day.n)?"active":""} onClick={()=>toggleDay(day.n)} key={day.n}>{form.daysOfWeek.includes(day.n)&&<Check size={13}/>}<span>{day.l}</span></button>)}</div></fieldset><div className="form-grid"><label><span>Início</span><input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label><span>Fim</span><input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div><label className="routine-active-toggle"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/><span>Rotina ativa para novas semanas</span></label></div><footer><button className="secondary-button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary-button" disabled={saving} onClick={()=>void save()}>{saving?"Salvando...":"Salvar rotina"}</button></footer></section></div>}
 </main>;
}
