"use client";

import { CalendarDays, Check, CircleDollarSign, FileText, MapPin, Pencil, Plane, Plus, Trash2 } from "lucide-react";
import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import { lifeosApi } from "@/lib/api";
import { Trip, TripDetails, TripInput } from "@/lib/types";
import { useResource } from "@/lib/use-resource";
import { SyncState } from "./sync-state";
import { EntityDrawer } from "./entity-drawer";
import { ConfirmDialog } from "./confirm-dialog";
import { useToast } from "./toast-provider";
import { Skeleton } from "./skeleton";

const emptyTrip: TripInput={name:"",destination:"",startDate:null,endDate:null,status:"PLANNING",currency:"BRL",budget:0,notes:"",coverEmoji:"✈️"};
const money=(value:number,currency:string)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency}).format(value||0);
const date=(value?:string|null)=>value?new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR"):"Sem data";

export function TripsView(){
  const loader=useCallback(()=>lifeosApi.trips(),[]);
  const {data:trips,setData:setTrips,loading,source,warning,error,reload}=useResource(loader,[] as Trip[]);
  const [selected,setSelected]=useState<string>(); const [details,setDetails]=useState<TripDetails>();
  const [form,setForm]=useState<TripInput>(emptyTrip); const [message,setMessage]=useState<string>(); const [tab,setTab]=useState("overview");
  const [drawerOpen,setDrawerOpen]=useState(false); const [editing,setEditing]=useState<string|null>(null); const [deleteTarget,setDeleteTarget]=useState<Trip|null>(null); const [saving,setSaving]=useState(false); const {notify}=useToast();
  const [detailsLoading,setDetailsLoading]=useState(false);
  const activeId=selected??trips[0]?.id;
  const loadDetails=useCallback(async(id:string)=>{setDetailsLoading(true);try{setDetails((await lifeosApi.trip(id)).data);setMessage(undefined)}catch(e){setMessage(e instanceof Error?e.message:"Falha ao carregar viagem.")}finally{setDetailsLoading(false)}},[]);
  useEffect(()=>{if(activeId)void loadDetails(activeId);else setDetails(undefined)},[activeId,loadDetails]);

  function openCreate(){setEditing(null);setForm(emptyTrip);setDrawerOpen(true)}
  function openEdit(trip:Trip){setEditing(trip.id);setForm({name:trip.name,destination:trip.destination,startDate:trip.startDate,endDate:trip.endDate,status:trip.status,currency:trip.currency,budget:trip.budget,notes:trip.notes,coverEmoji:trip.coverEmoji});setDrawerOpen(true)}
  async function saveTrip(e:FormEvent){e.preventDefault();if(!form.name.trim()||!form.destination.trim()){notify("Informe nome e destino.","error");return}setSaving(true);try{const saved=(editing?await lifeosApi.updateTrip(editing,form):await lifeosApi.createTrip(form)).data;setTrips(c=>editing?c.map(t=>t.id===editing?saved:t):[...c,saved]);setSelected(saved.id);setDrawerOpen(false);await loadDetails(saved.id);notify(editing?"Viagem atualizada.":"Viagem criada.")}catch(x){notify(x instanceof Error?x.message:"Falha ao salvar viagem.","error")}finally{setSaving(false)}}
  async function removeTrip(){if(!deleteTarget)return;setSaving(true);try{await lifeosApi.deleteTrip(deleteTarget.id);setTrips(c=>c.filter(t=>t.id!==deleteTarget.id));setSelected(undefined);setDetails(undefined);setDeleteTarget(null);notify("Viagem excluída.")}catch(x){notify(x instanceof Error?x.message:"Falha ao excluir viagem.","error")}finally{setSaving(false)}}
  const refresh=()=>activeId?loadDetails(activeId):Promise.resolve();
  const progress=details?.trip.checklistTotal?Math.round(details.trip.checklistDone/details.trip.checklistTotal*100):0;

  return <>
    <div className="resource-header"><SyncState loading={loading} source={source} warning={warning} error={error} onRetry={reload}/><button className="primary-button" onClick={openCreate}><Plus size={16}/> Nova viagem</button></div>
    {message?<p className="inline-message">{message}</p>:null}
    <div className="travel-layout">
      <aside className="trip-list panel">{loading?<TripListSkeleton/>:trips.length===0?<p className="empty-copy">Nenhuma viagem criada.</p>:trips.map(t=><button key={t.id} className={`trip-list-item ${activeId===t.id?"active":""}`} onClick={()=>setSelected(t.id)}><span>{t.coverEmoji}</span><div><strong>{t.name}</strong><small><MapPin size={12}/>{t.destination}</small><small>{date(t.startDate)} — {date(t.endDate)}</small></div></button>)}</aside>
      <section className="trip-workspace panel">{details?<>
        <header className="trip-hero"><div><span className="trip-emoji">{details.trip.coverEmoji}</span><p className="eyebrow small">{details.trip.status}</p><h2>{details.trip.name}</h2><p><MapPin size={15}/>{details.trip.destination} · {date(details.trip.startDate)} — {date(details.trip.endDate)}</p></div><div className="row-actions"><button className="icon-button ghost" onClick={()=>openEdit(details.trip)} title="Editar"><Pencil size={17}/></button><button className="icon-button ghost danger-icon" onClick={()=>setDeleteTarget(details.trip)} title="Excluir"><Trash2 size={17}/></button></div></header>
        <div className="trip-kpis"><div><span>Orçamento</span><strong>{money(details.trip.budget,details.trip.currency)}</strong></div><div><span>Gasto</span><strong>{money(details.trip.spent,details.trip.currency)}</strong></div><div><span>Disponível</span><strong>{money(details.trip.budget-details.trip.spent,details.trip.currency)}</strong></div><div><span>Checklist</span><strong>{progress}%</strong></div></div>
        <nav className="trip-tabs">{[["overview","Visão geral"],["itinerary","Roteiro"],["reservations","Reservas"],["documents","Documentos"],["checklist","Checklist"],["expenses","Orçamento"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
        {tab==="overview"?<Overview details={details}/>:null}
        {tab==="itinerary"?<Itinerary details={details} refresh={refresh}/>:null}
        {tab==="reservations"?<Reservations details={details} refresh={refresh}/>:null}
        {tab==="documents"?<Documents details={details} refresh={refresh}/>:null}
        {tab==="checklist"?<Checklist details={details} refresh={refresh}/>:null}
        {tab==="expenses"?<Expenses details={details} refresh={refresh}/>:null}
      </>:detailsLoading?<TripDetailsSkeleton/>:<div className="travel-empty"><Plane size={42}/><h3>Crie sua primeira viagem</h3><p>Todos os detalhes ficarão centralizados aqui.</p></div>}</section>
    </div>
    <EntityDrawer open={drawerOpen} onClose={()=>setDrawerOpen(false)} eyebrow={editing?"Editar viagem":"Nova viagem"} title={editing?form.name||"Editar viagem":"Planeje sua próxima experiência"} footer={<><button className="secondary-button" onClick={()=>setDrawerOpen(false)}>Cancelar</button><button className="primary-button" form="trip-editor-form" disabled={saving}>{saving?"Salvando…":editing?"Salvar alterações":"Criar viagem"}</button></>}>
      <form id="trip-editor-form" className="entity-form" onSubmit={saveTrip}>
        <div className="form-grid"><label className="field"><span>Emoji</span><input value={form.coverEmoji??"✈️"} onChange={e=>setForm({...form,coverEmoji:e.target.value})}/></label><label className="field"><span>Status</span><select value={form.status??"PLANNING"} onChange={e=>setForm({...form,status:e.target.value})}><option value="PLANNING">Planejando</option><option value="BOOKED">Reservada</option><option value="IN_PROGRESS">Em andamento</option><option value="COMPLETED">Concluída</option></select></label></div>
        <label className="field field-wide"><span>Nome</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Japão 2027"/></label>
        <label className="field field-wide"><span>Destino</span><input value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} placeholder="Cidade ou país"/></label>
        <div className="form-grid"><label className="field"><span>Início</span><input type="date" value={form.startDate??""} onChange={e=>setForm({...form,startDate:e.target.value||null})}/></label><label className="field"><span>Fim</span><input type="date" value={form.endDate??""} onChange={e=>setForm({...form,endDate:e.target.value||null})}/></label><label className="field"><span>Moeda</span><select value={form.currency??"BRL"} onChange={e=>setForm({...form,currency:e.target.value})}><option>BRL</option><option>USD</option><option>CAD</option><option>JPY</option><option>EUR</option><option>ARS</option></select></label><label className="field"><span>Orçamento</span><input type="number" min="0" step="0.01" value={form.budget??0} onChange={e=>setForm({...form,budget:Number(e.target.value)})}/></label></div>
        <label className="field field-wide"><span>Notas</span><textarea rows={6} value={form.notes??""} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Links, ideias e observações importantes"/></label>
      </form>
    </EntityDrawer>
    <ConfirmDialog open={Boolean(deleteTarget)} title="Excluir viagem?" description={`“${deleteTarget?.name??""}” e todos os roteiros, reservas, documentos, checklists e despesas serão removidos.`} onCancel={()=>setDeleteTarget(null)} onConfirm={()=>void removeTrip()} busy={saving}/>
  </>;
}

function Overview({details}:{details:TripDetails}){const cards=[{icon:CalendarDays,label:"Roteiro",value:`${details.itinerary.length} itens`},{icon:Plane,label:"Reservas",value:`${details.reservations.length} reservas`},{icon:FileText,label:"Documentos",value:`${details.documents.filter(x=>x.ready).length}/${details.documents.length} prontos`},{icon:Check,label:"Checklist",value:`${details.checklist.filter(x=>x.completed).length}/${details.checklist.length} concluídos`}];return <div className="travel-overview"><div className="travel-summary-grid">{cards.map(({icon:Icon,label,value})=><article key={label}><Icon size={20}/><span>{label}</span><strong>{value}</strong></article>)}</div><article className="trip-notes"><h3>Notas da viagem</h3><p>{details.trip.notes||"Adicione observações importantes, links e lembretes na edição da viagem."}</p></article></div>}

function Itinerary({details,refresh}:{details:TripDetails;refresh:()=>Promise<void>}){const [f,setF]=useState({itemDate:details.trip.startDate??new Date().toISOString().slice(0,10),startTime:"09:00",title:"",location:"",notes:"",completed:false});async function add(e:FormEvent){e.preventDefault();if(!f.title)return;await lifeosApi.addItinerary(details.trip.id,f);setF({...f,title:"",location:"",notes:""});await refresh()}return <Module title="Roteiro diário"><form className="travel-inline-form" onSubmit={add}><input type="date" value={f.itemDate} onChange={e=>setF({...f,itemDate:e.target.value})}/><input type="time" value={f.startTime} onChange={e=>setF({...f,startTime:e.target.value})}/><input placeholder="Atividade" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><input placeholder="Local" value={f.location} onChange={e=>setF({...f,location:e.target.value})}/><button>Adicionar</button></form><div className="travel-rows">{details.itinerary.map(i=><div className={i.completed?"done":""} key={i.id}><button className="travel-check" onClick={async()=>{await lifeosApi.toggleItinerary(details.trip.id,i.id);await refresh()}}>{i.completed?"✓":""}</button><strong>{date(i.itemDate)} {i.startTime?.slice(0,5)}</strong><span>{i.title}{i.location?` · ${i.location}`:""}</span><button onClick={async()=>{await lifeosApi.deleteItinerary(details.trip.id,i.id);await refresh()}}><Trash2 size={14}/></button></div>)}</div></Module>}
function Reservations({details,refresh}:{details:TripDetails;refresh:()=>Promise<void>}){const [f,setF]=useState({reservationType:"Voo",provider:"",confirmationCode:"",startAt:null as string|null,endAt:null as string|null,amount:0,notes:""});async function add(e:FormEvent){e.preventDefault();if(!f.provider)return;await lifeosApi.addReservation(details.trip.id,f);setF({...f,provider:"",confirmationCode:"",amount:0});await refresh()}return <Module title="Reservas"><form className="travel-inline-form" onSubmit={add}><select value={f.reservationType} onChange={e=>setF({...f,reservationType:e.target.value})}><option>Voo</option><option>Hotel</option><option>Passeio</option><option>Transporte</option></select><input placeholder="Empresa / local" value={f.provider} onChange={e=>setF({...f,provider:e.target.value})}/><input placeholder="Confirmação" value={f.confirmationCode} onChange={e=>setF({...f,confirmationCode:e.target.value})}/><input type="number" min="0" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:Number(e.target.value)})}/><button>Adicionar</button></form><div className="travel-cards">{details.reservations.map(r=><article key={r.id}><span>{r.reservationType}</span><h4>{r.provider}</h4><p>{r.confirmationCode||"Sem código"}</p><strong>{money(r.amount,details.trip.currency)}</strong><button onClick={async()=>{await lifeosApi.deleteReservation(details.trip.id,r.id);await refresh()}}><Trash2 size={14}/></button></article>)}</div></Module>}
function Documents({details,refresh}:{details:TripDetails;refresh:()=>Promise<void>}){const [f,setF]=useState({name:"",documentType:"Passaporte",reference:"",expiryDate:null as string|null,ready:false});async function add(e:FormEvent){e.preventDefault();if(!f.name)return;await lifeosApi.addTravelDocument(details.trip.id,f);setF({...f,name:"",reference:""});await refresh()}return <Module title="Documentos"><form className="travel-inline-form" onSubmit={add}><input placeholder="Documento" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select value={f.documentType} onChange={e=>setF({...f,documentType:e.target.value})}><option>Passaporte</option><option>Visto</option><option>Seguro</option><option>Ingresso</option><option>Outro</option></select><input placeholder="Número ou link" value={f.reference} onChange={e=>setF({...f,reference:e.target.value})}/><input type="date" value={f.expiryDate??""} onChange={e=>setF({...f,expiryDate:e.target.value||null})}/><button>Adicionar</button></form><div className="travel-rows">{details.documents.map(d=><div className={d.ready?"done":""} key={d.id}><button className="travel-check" onClick={async()=>{await lifeosApi.toggleTravelDocument(details.trip.id,d.id);await refresh()}}>{d.ready?"✓":""}</button><strong>{d.documentType}</strong><span>{d.name}{d.expiryDate?` · vence ${date(d.expiryDate)}`:""}</span><button onClick={async()=>{await lifeosApi.deleteTravelDocument(details.trip.id,d.id);await refresh()}}><Trash2 size={14}/></button></div>)}</div></Module>}
function Checklist({details,refresh}:{details:TripDetails;refresh:()=>Promise<void>}){const [f,setF]=useState({title:"",category:"Geral",completed:false});async function add(e:FormEvent){e.preventDefault();if(!f.title)return;await lifeosApi.addTripChecklist(details.trip.id,f);setF({...f,title:""});await refresh()}return <Module title="Checklist"><form className="travel-inline-form compact" onSubmit={add}><input placeholder="Item" value={f.title} onChange={e=>setF({...f,title:e.target.value})}/><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Geral</option><option>Mala</option><option>Documentos</option><option>Compras</option><option>Antes de sair</option></select><button>Adicionar</button></form><div className="travel-rows">{details.checklist.map(i=><div className={i.completed?"done":""} key={i.id}><button className="travel-check" onClick={async()=>{await lifeosApi.toggleTripChecklist(details.trip.id,i.id);await refresh()}}>{i.completed?"✓":""}</button><strong>{i.category}</strong><span>{i.title}</span><button onClick={async()=>{await lifeosApi.deleteTripChecklist(details.trip.id,i.id);await refresh()}}><Trash2 size={14}/></button></div>)}</div></Module>}
function Expenses({details,refresh}:{details:TripDetails;refresh:()=>Promise<void>}){const [f,setF]=useState({description:"",category:"Alimentação",amount:0,expenseDate:new Date().toISOString().slice(0,10),paid:true});const total=useMemo(()=>details.expenses.reduce((s,e)=>s+Number(e.amount),0),[details.expenses]);async function add(e:FormEvent){e.preventDefault();if(!f.description||f.amount<=0)return;await lifeosApi.addTripExpense(details.trip.id,f);setF({...f,description:"",amount:0});await refresh()}return <Module title={`Despesas · ${money(total,details.trip.currency)}`}><form className="travel-inline-form" onSubmit={add}><input placeholder="Descrição" value={f.description} onChange={e=>setF({...f,description:e.target.value})}/><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}><option>Alimentação</option><option>Hospedagem</option><option>Transporte</option><option>Passeios</option><option>Compras</option><option>Outros</option></select><input type="number" min="0.01" step="0.01" value={f.amount} onChange={e=>setF({...f,amount:Number(e.target.value)})}/><input type="date" value={f.expenseDate} onChange={e=>setF({...f,expenseDate:e.target.value})}/><button>Adicionar</button></form><div className="travel-rows">{details.expenses.map(x=><div key={x.id}><CircleDollarSign size={17}/><strong>{x.category}</strong><span>{x.description} · {date(x.expenseDate)}</span><b>{money(x.amount,details.trip.currency)}</b><button onClick={async()=>{await lifeosApi.deleteTripExpense(details.trip.id,x.id);await refresh()}}><Trash2 size={14}/></button></div>)}</div></Module>}
function Module({title,children}:{title:string;children:ReactNode}){return <section className="travel-module"><h3>{title}</h3>{children}</section>}

function TripListSkeleton(){return <>{Array.from({length:3}).map((_,index)=><div className="trip-list-item" key={index} aria-hidden="true"><Skeleton width={25} height={25} radius="50%"/><div style={{display:"grid",gap:5,minWidth:0,flex:1}}><Skeleton width="75%" height={13}/><Skeleton width="55%" height={10}/></div></div>)}</>}

function TripDetailsSkeleton(){return <div style={{padding:28}} aria-hidden="true">
  <Skeleton width={140} height={30}/>
  <Skeleton width="45%" height={14} style={{marginTop:14}}/>
  <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginTop:26}}>{Array.from({length:4}).map((_,index)=><Skeleton key={index} height={50}/>)}</div>
</div>}
