"use client";
import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, Check, ExternalLink, FileText, Kanban, LayoutList, Link2, Plus, Settings, Sparkles, Trash2 } from "lucide-react";
import { lifeosApi } from "@/lib/api";
import { WorkspaceAttachment, WorkspaceChecklistItem, WorkspaceDetail } from "@/lib/types";
import { useResource } from "@/lib/use-resource";
import { SyncState } from "./sync-state";
import { useToast } from "./toast-provider";

type Tab = "overview"|"board"|"list"|"calendar"|"timeline"|"knowledge"|"files"|"settings";
const tabs: Array<[Tab,string]> = [["overview","Overview"],["board","Board"],["list","Lista"],["calendar","Calendar"],["timeline","Timeline"],["knowledge","Knowledge"],["files","Files"],["settings","Settings"]];
export function WorkspaceDetailView({workspaceId}:{workspaceId:string}){
 const loader=useCallback(()=>lifeosApi.workspaceDetail(workspaceId),[workspaceId]);
 const {data,setData,loading,error,source,warning,reload}=useResource(loader,null as WorkspaceDetail|null);
 const [tab,setTab]=useState<Tab>("overview"); const [checkTitle,setCheckTitle]=useState(""); const [fileName,setFileName]=useState(""); const [fileUrl,setFileUrl]=useState(""); const {notify}=useToast();
 const grouped=useMemo(()=>({next:data?.tasks.filter(t=>t.status==="Próxima")??[],doing:data?.tasks.filter(t=>t.status==="Em andamento")??[],done:data?.tasks.filter(t=>t.status==="Concluída")??[]}),[data]);
 async function addCheck(){if(!checkTitle.trim()||!data)return;try{const r=await lifeosApi.addWorkspaceChecklist(workspaceId,checkTitle,data.checklist.length);setData({...data,checklist:[...data.checklist,r.data]});setCheckTitle("");notify("Item adicionado.");}catch(e){notify(e instanceof Error?e.message:"Falha ao adicionar.","error")}}
 async function toggleCheck(item:WorkspaceChecklistItem){if(!data)return;const r=await lifeosApi.toggleWorkspaceChecklist(workspaceId,item.id);setData({...data,checklist:data.checklist.map(x=>x.id===item.id?r.data:x)});}
 async function removeCheck(id:string){if(!data)return;await lifeosApi.deleteWorkspaceChecklist(workspaceId,id);setData({...data,checklist:data.checklist.filter(x=>x.id!==id)});}
 async function addFile(){if(!fileName.trim()||!fileUrl.trim()||!data)return;try{const r=await lifeosApi.addWorkspaceAttachment(workspaceId,{name:fileName,url:fileUrl});setData({...data,attachments:[r.data,...data.attachments]});setFileName("");setFileUrl("");notify("Link anexado.");}catch(e){notify(e instanceof Error?e.message:"Falha ao anexar.","error")}}
 async function removeFile(item:WorkspaceAttachment){if(!data)return;await lifeosApi.deleteWorkspaceAttachment(workspaceId,item.id);setData({...data,attachments:data.attachments.filter(x=>x.id!==item.id)});}
 if(loading||!data)return <SyncState loading={loading} error={error} source={source} warning={warning} onRetry={reload}/>;
 return <div className="workspace-detail-page"><Link className="back-link" href="/workspaces"><ArrowLeft size={16}/> Workspaces</Link><header className="workspace-detail-hero"><div><span className="eyebrow">{data.area} · {data.type}</span><h1>{data.name}</h1><p>{data.description||"Workspace sem descrição."}</p></div><div className="workspace-health-ring"><strong>{data.progress}%</strong><span>progresso</span></div></header><nav className="workspace-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="overview"&&<section className="workspace-detail-grid"><article className="panel workspace-overview-card"><h3>Próximas ações</h3>{data.tasks.filter(t=>t.status!=="Concluída").slice(0,6).map(t=><div className="workspace-line" key={t.id}><span className="task-check"/><div><strong>{t.title}</strong><small>{t.priority} · {t.context}</small></div></div>)}</article><article className="panel workspace-overview-card"><h3>Checklist</h3><div className="inline-create"><input value={checkTitle} onChange={e=>setCheckTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void addCheck()}} placeholder="Adicionar item"/><button onClick={()=>void addCheck()}><Plus size={15}/></button></div>{data.checklist.map(i=><div className="workspace-line" key={i.id}><button className="task-check" onClick={()=>void toggleCheck(i)}>{i.completed?<Check size={13}/>:null}</button><span className={i.completed?"completed-text":""}>{i.title}</span><button className="icon-button ghost" onClick={()=>void removeCheck(i.id)}><Trash2 size={13}/></button></div>)}</article><article className="panel workspace-overview-card"><h3>Notas recentes</h3>{data.notes.slice(0,5).map(n=><div className="workspace-line" key={n.id}><FileText size={16}/><div><strong>{n.title}</strong><small>{new Date(n.updatedAt).toLocaleDateString("pt-BR")}</small></div></div>)}</article><article className="panel workspace-overview-card"><h3>Resumo</h3><div className="workspace-metrics"><div><strong>{data.tasks.length}</strong><span>tarefas</span></div><div><strong>{data.notes.length}</strong><span>notas</span></div><div><strong>{data.attachments.length}</strong><span>arquivos</span></div><div><strong>{data.timeline.length}</strong><span>eventos</span></div></div></article></section>}
 {tab==="board"&&<section className="workspace-board">{[["A fazer",grouped.next],["Em andamento",grouped.doing],["Concluído",grouped.done]].map(([title,items])=><div className="workspace-column" key={title as string}><header><span><Kanban size={14}/>{title as string}</span><strong>{(items as typeof data.tasks).length}</strong></header><div className="workspace-cards">{(items as typeof data.tasks).map(t=><article className="workspace-task-card" key={t.id}><strong>{t.title}</strong><span>{t.context} · {t.priority}</span></article>)}</div></div>)}</section>}
 {tab==="list"&&<section className="panel workspace-table"><header><LayoutList size={17}/><strong>Todas as tarefas</strong></header>{data.tasks.map(t=><div key={t.id}><strong>{t.title}</strong><span>{t.status}</span><span>{t.priority}</span><span>{t.dueDate?new Date(t.dueDate+"T12:00:00").toLocaleDateString("pt-BR"):"Sem prazo"}</span></div>)}</section>}
 {tab==="calendar"&&<section className="panel workspace-empty-tab"><CalendarDays size={30}/><h3>Calendário do workspace</h3><p>{data.tasks.filter(t=>t.dueDate).length} tarefas possuem data definida. A visualização usa os prazos do workspace.</p>{data.tasks.filter(t=>t.dueDate).map(t=><div className="workspace-line" key={t.id}><strong>{new Date(t.dueDate!+"T12:00:00").toLocaleDateString("pt-BR")}</strong><span>{t.title}</span></div>)}</section>}
 {tab==="timeline"&&<section className="panel workspace-timeline">{data.timeline.map(e=><article key={e.id}><span/><div><strong>{e.description}</strong><small>{new Date(e.createdAt).toLocaleString("pt-BR")} · {e.entityType}</small></div></article>)}</section>}
 {tab==="knowledge"&&<section className="workspace-detail-grid">{data.notes.map(n=><article className="panel workspace-note-card" key={n.id}><span className="eyebrow">{n.favorite?"Favorita":"Nota"}</span><h3>{n.title}</h3><p>{n.content.slice(0,220)||"Nota vazia"}</p></article>)}</section>}
 {tab==="files"&&<section className="panel workspace-files"><div className="file-create"><input placeholder="Nome do arquivo ou link" value={fileName} onChange={e=>setFileName(e.target.value)}/><input placeholder="https://..." value={fileUrl} onChange={e=>setFileUrl(e.target.value)}/><button className="primary-button" onClick={()=>void addFile()}><Link2 size={15}/> Anexar link</button></div>{data.attachments.map(a=><article key={a.id}><ExternalLink size={17}/><a href={a.url} target="_blank" rel="noreferrer"><strong>{a.name}</strong><small>{a.url}</small></a><button className="icon-button ghost" onClick={()=>void removeFile(a)}><Trash2 size={14}/></button></article>)}</section>}
 {tab==="settings"&&<section className="panel workspace-empty-tab"><Settings size={30}/><h3>Configurações</h3><p>Status: {data.status} · Tipo: {data.type} · Área: {data.area}</p><Link className="secondary-button" href="/workspaces">Editar pela central de Workspaces</Link></section>}
 </div>
}
