"use client";
import Link from "next/link";
import { useCallback, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, Check, ExternalLink, FileText, Kanban, LayoutList, Link2, Plus, Save, Settings, Trash2 } from "lucide-react";
import { lifeosApi } from "@/lib/api";
import { TaskStatus, WorkspaceAttachment, WorkspaceChecklistItem, WorkspaceDetail, WorkspaceTaskItem } from "@/lib/types";
import { useResource } from "@/lib/use-resource";
import { SyncState } from "./sync-state";
import { useToast } from "./toast-provider";

type Tab = "overview"|"board"|"list"|"calendar"|"timeline"|"knowledge"|"files"|"settings";
const tabs: Array<[Tab,string]> = [["overview","Overview"],["board","Board"],["list","Lista"],["calendar","Calendar"],["timeline","Timeline"],["knowledge","Knowledge"],["files","Files"],["settings","Settings"]];
const statuses:TaskStatus[]=["Próxima","Em andamento","Concluída"];

export function WorkspaceDetailView({workspaceId}:{workspaceId:string}){
 const loader=useCallback(()=>lifeosApi.workspaceDetail(workspaceId),[workspaceId]);
 const {data,setData,loading,error,source,warning,reload}=useResource(loader,null as WorkspaceDetail|null);
 const [tab,setTab]=useState<Tab>("overview");
 const [checkTitle,setCheckTitle]=useState(""); const [fileName,setFileName]=useState(""); const [fileUrl,setFileUrl]=useState("");
 const [noteTitle,setNoteTitle]=useState(""); const [noteContent,setNoteContent]=useState("");
 const [savingSettings,setSavingSettings]=useState(false); const {notify}=useToast();
 const grouped=useMemo(()=>Object.fromEntries(statuses.map(status=>[status,data?.tasks.filter(t=>t.status===status)??[]])) as Record<TaskStatus,WorkspaceTaskItem[]>,[data]);
 async function addCheck(){if(!checkTitle.trim()||!data)return;try{const r=await lifeosApi.addWorkspaceChecklist(workspaceId,checkTitle,data.checklist.length);setData({...data,checklist:[...data.checklist,r.data]});setCheckTitle("");notify("Item adicionado.");}catch(e){notify(e instanceof Error?e.message:"Falha ao adicionar.","error")}}
 async function toggleCheck(item:WorkspaceChecklistItem){if(!data)return;try{const r=await lifeosApi.toggleWorkspaceChecklist(workspaceId,item.id);setData({...data,checklist:data.checklist.map(x=>x.id===item.id?r.data:x)});}catch(e){notify(e instanceof Error?e.message:"Falha ao atualizar.","error")}}
 async function removeCheck(id:string){if(!data)return;try{await lifeosApi.deleteWorkspaceChecklist(workspaceId,id);setData({...data,checklist:data.checklist.filter(x=>x.id!==id)});}catch(e){notify(e instanceof Error?e.message:"Falha ao excluir.","error")}}
 async function addFile(){if(!fileName.trim()||!fileUrl.trim()||!data)return;try{new URL(fileUrl);const r=await lifeosApi.addWorkspaceAttachment(workspaceId,{name:fileName,url:fileUrl});setData({...data,attachments:[r.data,...data.attachments]});setFileName("");setFileUrl("");notify("Link anexado.");}catch(e){notify(e instanceof Error?e.message:"URL inválida ou falha ao anexar.","error")}}
 async function removeFile(item:WorkspaceAttachment){if(!data)return;try{await lifeosApi.deleteWorkspaceAttachment(workspaceId,item.id);setData({...data,attachments:data.attachments.filter(x=>x.id!==item.id)});}catch(e){notify(e instanceof Error?e.message:"Falha ao excluir.","error")}}
 async function changeTaskStatus(task:WorkspaceTaskItem,status:TaskStatus){if(!data||task.status===status)return;const previous=data;setData({...data,tasks:data.tasks.map(t=>t.id===task.id?{...t,status}:t)});try{await lifeosApi.updateTaskStatus(task.id,status);await reload();}catch(e){setData(previous);notify(e instanceof Error?e.message:"Falha ao mover tarefa.","error")}}
 async function createNote(){if(!data||!noteTitle.trim())return;try{await lifeosApi.createNote({title:noteTitle.trim(),content:noteContent,projectId:workspaceId});setNoteTitle("");setNoteContent("");await reload();notify("Nota criada no workspace.");}catch(e){notify(e instanceof Error?e.message:"Falha ao criar nota.","error")}}
 async function saveSettings(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!data)return;const form=new FormData(event.currentTarget);setSavingSettings(true);try{await lifeosApi.updateProject(workspaceId,{name:String(form.get("name")||data.name),description:String(form.get("description")||""),area:String(form.get("area")||"Pessoal"),type:data.type,icon:data.icon,color:data.color,status:String(form.get("status")||"ACTIVE"),startDate:String(form.get("startDate")||"")||null,dueDate:String(form.get("dueDate")||"")||null,metadata:"{}"});await reload();notify("Workspace atualizado.");}catch(e){notify(e instanceof Error?e.message:"Falha ao salvar.","error")}finally{setSavingSettings(false)}}
 if(loading||!data)return <SyncState loading={loading} error={error} source={source} warning={warning} onRetry={reload}/>;
 return <div className="workspace-detail-page"><Link className="back-link" href="/workspaces"><ArrowLeft size={16}/> Workspaces</Link><header className="workspace-detail-hero"><div><span className="eyebrow">{data.area} · {data.type}</span><h1>{data.name}</h1><p>{data.description||"Workspace sem descrição."}</p></div><div className="workspace-health-ring"><strong>{data.progress}%</strong><span>progresso</span></div></header><nav className="workspace-tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>
 {tab==="overview"&&<section className="workspace-detail-grid"><article className="panel workspace-overview-card"><h3>Próximas ações</h3>{data.tasks.filter(t=>t.status!=="Concluída").slice(0,6).map(t=><div className="workspace-line" key={t.id}><button className="task-check" aria-label={`Concluir ${t.title}`} onClick={()=>void changeTaskStatus(t,"Concluída")}/><div><strong>{t.title}</strong><small>{t.priority} · {t.context}</small></div></div>)}{!data.tasks.some(t=>t.status!=="Concluída")&&<p>Nenhuma ação pendente.</p>}</article><article className="panel workspace-overview-card"><h3>Checklist</h3><div className="inline-create"><input value={checkTitle} onChange={e=>setCheckTitle(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")void addCheck()}} placeholder="Adicionar item"/><button onClick={()=>void addCheck()}><Plus size={15}/></button></div>{data.checklist.map(i=><div className="workspace-line" key={i.id}><button className="task-check" onClick={()=>void toggleCheck(i)}>{i.completed?<Check size={13}/>:null}</button><span className={i.completed?"completed-text":""}>{i.title}</span><button className="icon-button ghost" onClick={()=>void removeCheck(i.id)}><Trash2 size={13}/></button></div>)}</article><article className="panel workspace-overview-card"><h3>Notas recentes</h3>{data.notes.slice(0,5).map(n=><div className="workspace-line" key={n.id}><FileText size={16}/><div><strong>{n.title}</strong><small>{new Date(n.updatedAt).toLocaleDateString("pt-BR")}</small></div></div>)}</article><article className="panel workspace-overview-card"><h3>Resumo</h3><div className="workspace-metrics"><div><strong>{data.tasks.length}</strong><span>tarefas</span></div><div><strong>{data.notes.length}</strong><span>notas</span></div><div><strong>{data.attachments.length}</strong><span>arquivos</span></div><div><strong>{data.timeline.length}</strong><span>eventos</span></div></div></article></section>}
 {tab==="board"&&<section className="workspace-board">{statuses.map(status=><div className="workspace-column" key={status}><header><span><Kanban size={14}/>{status}</span><strong>{grouped[status].length}</strong></header><div className="workspace-cards">{grouped[status].map(t=><article className="workspace-task-card" key={t.id}><strong>{t.title}</strong><span>{t.context} · {t.priority}</span><select aria-label={`Status de ${t.title}`} value={t.status} onChange={e=>void changeTaskStatus(t,e.target.value as TaskStatus)}>{statuses.map(value=><option key={value}>{value}</option>)}</select></article>)}</div></div>)}</section>}
 {tab==="list"&&<section className="panel workspace-table"><header><LayoutList size={17}/><strong>Todas as tarefas</strong></header>{data.tasks.map(t=><div key={t.id}><strong>{t.title}</strong><select value={t.status} onChange={e=>void changeTaskStatus(t,e.target.value as TaskStatus)}>{statuses.map(value=><option key={value}>{value}</option>)}</select><span>{t.priority}</span><span>{t.dueDate?new Date(t.dueDate+"T12:00:00").toLocaleDateString("pt-BR"):"Sem prazo"}</span></div>)}</section>}
 {tab==="calendar"&&<section className="panel workspace-empty-tab"><CalendarDays size={30}/><h3>Calendário do workspace</h3><p>{data.tasks.filter(t=>t.dueDate).length} tarefas possuem data definida.</p>{data.tasks.filter(t=>t.dueDate).sort((a,b)=>a.dueDate!.localeCompare(b.dueDate!)).map(t=><div className="workspace-line" key={t.id}><strong>{new Date(t.dueDate!+"T12:00:00").toLocaleDateString("pt-BR")}</strong><button className="task-check" onClick={()=>void changeTaskStatus(t,"Concluída")}>{t.status==="Concluída"?<Check size={13}/>:null}</button><span className={t.status==="Concluída"?"completed-text":""}>{t.title}</span></div>)}</section>}
 {tab==="timeline"&&<section className="panel workspace-timeline">{data.timeline.map(e=><article key={e.id}><span/><div><strong>{e.description}</strong><small>{new Date(e.createdAt).toLocaleString("pt-BR")} · {e.entityType}</small></div></article>)}</section>}
 {tab==="knowledge"&&<><section className="panel workspace-note-create"><h3>Nova nota</h3><input value={noteTitle} onChange={e=>setNoteTitle(e.target.value)} placeholder="Título"/><textarea rows={5} value={noteContent} onChange={e=>setNoteContent(e.target.value)} placeholder="Conteúdo em Markdown"/><button className="primary-button" onClick={()=>void createNote()}><Plus size={15}/> Criar nota</button></section><section className="workspace-detail-grid">{data.notes.map(n=><Link href={`/brain?note=${n.id}`} className="panel workspace-note-card" key={n.id}><span className="eyebrow">{n.favorite?"Favorita":"Nota"}</span><h3>{n.title}</h3><p>{n.content.slice(0,220)||"Nota vazia"}</p></Link>)}</section></>}
 {tab==="files"&&<section className="panel workspace-files"><div className="file-create"><input placeholder="Nome do arquivo ou link" value={fileName} onChange={e=>setFileName(e.target.value)}/><input type="url" placeholder="https://..." value={fileUrl} onChange={e=>setFileUrl(e.target.value)}/><button className="primary-button" onClick={()=>void addFile()}><Link2 size={15}/> Anexar link</button></div>{data.attachments.map(a=><article key={a.id}><ExternalLink size={17}/><a href={a.url} target="_blank" rel="noreferrer"><strong>{a.name}</strong><small>{a.url}</small></a><button className="icon-button ghost" onClick={()=>void removeFile(a)}><Trash2 size={14}/></button></article>)}</section>}
 {tab==="settings"&&<section className="panel workspace-settings"><div><Settings size={30}/><h3>Configurações do workspace</h3></div><form className="entity-form" onSubmit={saveSettings}><label className="field field-wide"><span>Nome</span><input name="name" defaultValue={data.name} required/></label><label className="field field-wide"><span>Descrição</span><textarea name="description" rows={5} defaultValue={data.description}/></label><div className="form-grid"><label className="field"><span>Área</span><input name="area" defaultValue={data.area}/></label><label className="field"><span>Status</span><select name="status" defaultValue={data.status}><option value="ACTIVE">Ativo</option><option value="PAUSED">Pausado</option><option value="COMPLETED">Concluído</option></select></label><label className="field"><span>Início</span><input name="startDate" type="date" defaultValue={data.startDate??""}/></label><label className="field"><span>Prazo</span><input name="dueDate" type="date" defaultValue={data.dueDate??""}/></label></div><button className="primary-button" disabled={savingSettings}><Save size={15}/>{savingSettings?"Salvando...":"Salvar configurações"}</button></form></section>}
 </div>
}
